#For configuring locust script
[locust script]
locustfile: CompleteBookingSolution_MutipleUser_ExternalCSV.py
#host: http://newtours.demoaut.com

#For configuring worker mode
[locust worker mode]
worker: true
master-host: 127.0.0.1
master-port: 5557


[locust headless]
#headless: true
#users:5
#hatch-rate: 1
#run-time: 20s






